# Action to deploy py app to AWS
name: CI/CD-to-AWS
env:
  EB_PACKAGE_S3_BUCKET_NAME: "hetmanskyi-application1-packages"
  EB_APPLICATION_NAME: "My-py-app"
  EB_ENVIRONMENT_NAME: "My-py-env"
  DEPLOY_PACKAGE_NAME: "py_app_${{ github.sha }}.zip"
  AWS_REGION: "us-east-1"
  
on:
  push:
    branches:
      - main

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository with py app
      uses: actions/checkout@v3

    - name: Archive app
      run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*

    - name: Configure my AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with: 
        aws-access-key-id: ${{ secrets.AWS_GHA_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_GHA_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Copy archive to s3 bucket
      run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}/

    - name: Print message for CI finish
      run: echo "CI part. You have successfully deploy your app to s3 bucket!!!"
